### ISSUE TITLE
bad argument #1 to 'ipairs'

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#1]
I just installed and opened with <kbd><leader>k</kbd> and hit this:
<img width="1274" alt="image" src="https://github.com/Ramilito/kubectl.nvim/assets/17252601/8d570ab7-0342-4bcc-a064-418d28277abb">

**Comment by Ramilito** [comment]
I think this is caused by some pods not having any containerstatus field, added a check to skip that when it happens, could you update and check if that solved it?

**Comment by Ramilito** [comment]
I'm guessing this is ok now?
