### ISSUE TITLE
[Feature] Kubediff

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#11]
**Describe the solution you'd like**

 Diff capability

**Additional context**

What scope should this cover?
- Single file?
- Single file with multiple resources in one file?
- Kustomize whole overlays?
- Complete folders?

**Comment by Ramilito** [comment]
@mosheavni Could you expand on the use case? 
Please take a look at https://github/ramilito/kubediff and compare it with the way you are currently working?

**Comment by mosheavni** [comment]
sure
I set  the env var `KUBECTL_EXTERNAL_DIFF` to `kdiff`
`kdiff` is an executable that looks like this:
```
#!/bin/bash
nvim -c "DirDiff $1 $2"
```

the flow looks like this:

![2024-07-07_14-31-41](https://github.com/Ramilito/kubectl.nvim/assets/17252601/c6240622-1684-4622-bddd-cd8183efe347)

**Comment by Ramilito** [comment]
Implemented in #96!

You can use both [Kubediff](https://github.com/Ramilito/kubediff) or DirDiff
