### ISSUE TITLE
sorting with s collides with a plugin

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#112]
I'm using <kbd>s</kbd> for a plugin, can you either `remap = false` or allow overriding the sort keymap?
thanks.

**Comment by Ramilito** [comment]
Yeah I'm a bit torn on the keymaps atm, I will make them configurable soon but I first wanted to make good defaults and not really sure yet how I want them to work.

For now though, I made it not override anything in this commit 10a4a6931dba670521e5b2497f444bb2b24a1500.
Hope it works!

**Comment by mosheavni** [comment]
> Yeah I'm a bit torn on the keymaps atm, I will make them configurable soon but I first wanted to make good defaults and not really sure yet how I want them to work.
> 
> For now though, I made it not override anything in this commit [10a4a69](https://github.com/Ramilito/kubectl.nvim/commit/10a4a6931dba670521e5b2497f444bb2b24a1500). Hope it works!

that's fine for now thanks!
