### ISSUE TITLE
set all buffers to nomodifiable

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#116]
Set all buffers to `vim.opt.modifiable = false` so we cannot manipulate text on those buffers

**Comment by Ramilito** [comment]
I'm a bit torn about this one, my intention has been that we can toggle auto-refresh and then we have everything in a buffer to manipulate, not sure to what end yet.
What's bothering you about the buffer being modifiable?

**Comment by mosheavni** [comment]
> I'm a bit torn about this one, my intention has been that we can toggle auto-refresh and then we have everything in a buffer to manipulate, not sure to what end yet. What's bothering you about the buffer being modifiable?

i can accidently change the line content without intending to.
I don't see a reason to allow it to be modifiable.
can't auto refresh be mapped to some key like the others?

**Comment by Ramilito** [comment]
> i can accidently change the line content without intending to.

If you don't have auto-refresh and you accidentally modified the buffer you can just press R to undo that. Would that resolve the annoyance? 

> can't auto refresh be mapped to some key like the others?

The mapping wasn't the issue, when auto refresh is on it will redraw and remove all changes you did automatically so  you would never have the chance to modify it properly.

What I wanted to do in the future was a binding to toggle the auto_refresh off so the buffer can be modified in peace and the reasons aren't super clear for me yet but I have some vague idea of wanting to save certain views, maybe do bulk actions.

**Comment by mosheavni** [comment]
not sure i understand.. nvm.
