### ISSUE TITLE
feat: override keymaps

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#120]
**Describe the solution you'd like**

Not sure here, the best would be to use the Plug feature.

**Describe alternatives you've considered**

The normal mappings setup

**Comment by mosheavni** [comment]
`<Plug>` keymaps are the best way to go.

**Comment by Ramilito** [comment]
This is solved in #273, we still need to update docs on how to use it.

**Comment by Ramilito** [comment]
We have an issue to update docs so will close this one!
