### ISSUE TITLE
port forward icon not updated immediately

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#124]
hey
thank you for all the work!
amazing stuff

when I port-forward, I expect to see the icon of the port forward immediately. what happens in reality is i need to <kbd>gr</kbd> before the icon appears.

also, the header is too long - we had this issue before in other buffers
<img width="1541" alt="image" src="https://github.com/user-attachments/assets/5d4f3baa-a449-4ca3-8942-c4c661e00b3e">

also, the port forward details popup should and can be much much smaller, no need for this entirely huge float buffer

**Comment by Ramilito** [comment]
Thanks for the instant feedback 🙏 

Forgot about the divider hack for floating buffers, will need to do a better solution for that.
The bugs should be resolved on latest, will do the smaller floats next!

**Comment by Ramilito** [comment]
Just curious, have you tried the auto_refresh feature? I'm quite happy with it my self:

```

auto_refresh = {
    enabled = true,
    interval = 3000, -- milliseconds
  },

```

**Comment by Ramilito** [comment]
I just updated it to be on by default, if you don't like it just put enabled to false!

Closing this issue and opening a new one that handles the smaller buffer, was harder than expected
