### ISSUE TITLE
feat: hierchial view

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#130]
**Describe the solution you'd like**

I way to visualize the whole app hierarchically.

**Describe alternatives you've considered**

Either we do this in this plugin or use an external tool such as kubectl lineage

**Comment by mosheavni** [comment]
yes i love kube lineage.
did you think of requiring it as a submodule or optional dependency not managed by this plugin?

**Comment by Ramilito** [comment]
Yeah the easiest would be optional but that we offer some kind of integration for ux, similar to the diff integration

**Comment by mosheavni** [comment]
<img width="795" alt="image" src="https://github.com/user-attachments/assets/4e392072-034b-454a-8660-53565c40632d">
6.218 seconds using `kubectl-tree`
13.111 seconds using `kubectl-lineage`
and that's only 1 resource.

I'd say write something of our own.
