### ISSUE TITLE
feat: aliases performance

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#139]
**Is your feature request related to a problem? Please describe.**

Aliases view takes too long in some instances, we should cache those results.
Investigate preloading the buffer as well

**Describe the solution you'd like**

Simple cache, maybe once per session or once per day

**Comment by Ramilito** [comment]
@mosheavni Could you confirm if this solved the issue please 🙏?

**Comment by mosheavni** [comment]
Extremely faster now! thank you.
