### ISSUE TITLE
Secrets are going to fallback view

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#151]
When getting secrets through the alias menu:
<kbd>\<C-a></kbd>
secret
I get the fallback menu for secrets
When I run `:Kubectl get secret` I get the right secrets view.
Why on aliases it goes to fallback?
thanks.

**Comment by Ramilito** [comment]
Yeah, we aren't using the lookup table so it has to match the actual module name (lua folder), I changed that in #152 to use a lookup table for our views instead so we can now do:
<C-a>
sec

Or other shortcuts!
