### ISSUE TITLE
Mapping exit to 'q' causes plugin to crash after entering resource

### ISSUE THREAD

**Issue by rafi** [Ramilito/kubectl.nvim#165]
**Describe the bug**
Use following setup with lazy.nvim:
```lua
	{
		'ramilito/kubectl.nvim',
		keys = {
			{ '<leader>8', function() vim.cmd[[tabnew]]; require('kubectl').open() end, desc = 'Kubectl' },
		},
		opts = {
			mappings = {
				exit = 'q',
			},
		},
	},
```

**To Reproduce**
1. Open with <kbd>Leader</kbd><kbd>8</kbd>
2. Press <kbd>Return</kbd> on one of the resources
3. Press <kbd>q</kbd>

Error:
```
curl: (7) Failed to connect to 127.0.0.1 port 51069 after 0 ms: Couldn't connect to server
```

**Environment**
 - macOS 14.5
 - NVIM v0.11.0-dev-3755+g9768e88f3-Homebrew

**Comment by Ramilito** [comment]
Thank you for reporting this issue!

We do some cleaning up when triggering the exit mapping that shouldn't be done when closing a floating buffer, added a check in #166 to avoid stopping the kubectl proxy if we are close on a floating buffer

**Comment by rafi** [comment]
That was really fast :) works great!

**Comment by Ramilito** [comment]
Couldn't have done it so fast without the excellent issue description!
