### ISSUE TITLE
add `close` and `toggle` methods

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#174]
right now we open the plugin with `<cmd>lua require("kubectl").open()<cr>`
and then we map <kbd>\<leader>k</kbd> to close the plugin.
it would be better to not define:
https://github.com/Ramilito/kubectl.nvim/blob/f6575b9b7f96640195953c89b2d87f594220a124/lua/kubectl/mappings.lua#L10
and just allow the user to map his own `<cmd>lua require("kubectl").toggle()<cr>`
and add a `require("kubectl").close()`, again to allow the user for customization.

**Comment by Ramilito** [comment]
Yeah that might be more intuitive.
Just to be clear, are you suggesting we expose three functions ```open ``` ```close``` ```toggle``` or just ```open``` and ```close```?

**Comment by mosheavni** [comment]
> Yeah that might be more intuitive. Just to be clear, are you suggesting we expose three functions `open ` `close` `toggle` or just `open` and `close`?

yes all three, that's the way most plugins work and I think it is more intuitive as you stated.

**Comment by halshar** [comment]
yes, three would be better. Right now I've to open the the tool in another vim buffer as its easier for me to switch buffers than close and open the tool, toggle option would be much helpful

**Comment by Ramilito** [comment]
This is fixed in #183, thank you all for the awesome suggestions ❤️
