### ISSUE TITLE
errors when sorting and then changing NS

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#176]
**Describe the bug**
When sorting by age, then changing namespace, there are a lot of errors popping:
![2024-08-18_12-22-57 (1)](https://github.com/user-attachments/assets/f0ecb715-cb33-4b64-a60a-f21bdf90eff6)
```
Error executing vim.schedule lua callback: /Users/mavni/Repos/kubectl.nvim/lua/kubectl/utils/marks.lua:60: Invalid 'col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        /Users/mavni/Repos/kubectl.nvim/lua/kubectl/utils/marks.lua:60: in function 'set_virtual_text_on_mark'
        /Users/mavni/Repos/kubectl.nvim/lua/kubectl/utils/marks.lua:50: in function 'set_sortby_header'
        ...mavni/Repos/kubectl.nvim/lua/kubectl/resourcebuilder.lua:317: in function <...mavni/Repos/kubectl.nvim/lua/kubectl/resourcebuilder.lua:316>
```
When sorting by name, an additional NAME column is added:
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/d83ad572-38e5-49f5-a497-cbd57da5be32">

**To Reproduce**
1. Open fresh neovim window
2. Open Kubectl plugin
3. Sort by age
4. switch namespace
5. errors pop

**Comment by Ramilito** [comment]
Nice catch!

I messed up forgetting about the width shifting when filtering/changing namespace, it should be fixed now!
