### ISSUE TITLE
Switching between fallback doesn't change the title

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#192]
![2024-08-22_12-18-22 (1)](https://github.com/user-attachments/assets/1879860b-1d05-48bd-95f5-9d4966636431)

When viewing the fallback view for a resource, and changing to a different fallback view, the title doesn't update.
in the above example, I first get `externalsecrets`, then `clusterrole` then `ingresses`

**Comment by Ramilito** [comment]
Yeah I can see why, I'll see if I can fix it right away

**Comment by Ramilito** [comment]
#193 Should fix this!
