### ISSUE TITLE
Allow overriding keymaps

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#202]
I want to be able to use <kbd>0</kbd> to go to the start of the lines and not go to the root view.
better to allow overriding every keymap setting since it may override some plugin mapping.

**Comment by Ramilito** [comment]
You are correct, I removed that binding until we find a better solution, will close this issue since we have a similar one in #120  

About the root view, will open a discussion on it since I'm not sure where to go with it anymore.
