### ISSUE TITLE
feat: allow editing the yaml file in-place

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#214]
a super cool feature of k8s is that you can click <kbd>y</kbd> and you go to $EDITOR to edit the yaml.
Since we're already on vim, opening a terminal causes us to opening a vim inside vim (like inception).
We need to copy the logic behind `kubectl edit {resource}` to get the temporary file we're editing and maybe an autocommand for when the file is closed and saved, send that file to the server (I believe that's what they do behind the scenes).
WDYT @Ramilito ?

**Comment by Ramilito** [comment]
Maybe ```ge``` isn't working for you? I'm using it quite often and haven't had issues with it:

![ge](https://github.com/user-attachments/assets/5a159c10-0ec2-4956-9485-f5fd4ced5933)

**Comment by mosheavni** [comment]
> Maybe `ge` isn't working for you? I'm using it quite often and haven't had issues with it:
> 
> ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo) [ ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo) ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo) [ ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)

There are problems with this vimception.
When I use a `vim.ui.select` menu, then use `q` to exit, it exits also the inception vim edit window. that's far from ideal.
I'll try to attack this issue now.

**Comment by mosheavni** [comment]
I'll write a new logic for edit that can be shared across all resources.
Where should I place the function?

**Comment by Ramilito** [comment]
You can start where ever until it works and then we make it pretty, imo that's the best way of working 👍

**Comment by Ramilito** [comment]
> > Maybe `ge` isn't working for you? I'm using it quite often and haven't had issues with it:
> > ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >       
> >         [
> >           
> >             ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >           
> >         ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >         
> >        [ ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo) ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >       
> >         [
> >           
> >             ![ge](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >           
> >         ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/8473233/360858899-5a159c10-0ec2-4956-9485-f5fd4ced5933.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjI2MDgsIm5iZiI6MTcyNDQyMjMwOCwicGF0aCI6Ii84NDczMjMzLzM2MDg1ODg5OS01YTE1OWMxMC0wZWMyLTQ5NTYtOTQ4NS1mNWZkNGNlZDU5MzMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQxMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI2MGUxMjY3MDUwNGEyMTkyY2EyMWQ5NDgzMDBiZTA5MjAwMTMyZDg0YjA1Y2MxMWZlY2VmZmYzOTE2MjI3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sj52k6FVEI8tI-C_425QGPPRbVJamTe-eB4kLTm39Xo)
> 
> There are problems with this vimception. When I use a `vim.ui.select` menu, then use `q` to exit, it exits also the inception vim edit window. that's far from ideal. I'll try to attack this issue now.

That does sound inconvenient, just curious though, I'm able to press q without closing the edit view, none of the plugin bindings are triggering as long as I'm in the edit view.
How does your workflow work? are you getting snippets or something?
