### ISSUE TITLE
feat: clicking on deployment shows relevant pods

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#223]
When on deployments or daemonsets page, clicking <kbd>\<enter></kbd> should show me pod view with the specific workload pods I chose before.

I'm not sure if that's easy since we have filter but filter is not quite right for this.
and using `ownerReference` field is not straight forward because the direct owner of pods is a replicaset and not a deployment.

**Comment by Ramilito** [comment]
Yeah it's confusing and I think we should not have this behavior at all anymore (it was tied to the old plans of navigation)
We should use enter for something else in deployment and daemonset, any suggestions here?

**Comment by Ramilito** [comment]
Hmm maybe we could use the kubectl lineage here?!

**Comment by mosheavni** [comment]
> Hmm maybe we could use the kubectl lineage here?!

I also though about it but since we don't intend of requiring it as a dependency, getting something working along these lines is a must.
I created a draft PR.
It works excellent, although I really don't know how to change the view back to all pods
see #225

**Comment by Ramilito** [comment]
Thank you for pointing that out 👍
