### ISSUE TITLE
feat: more views

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#23]
**Describe the solution you'd like**

A list of views we want:

- [x] CRDS
- [x] ClusterRoleBindings
- [x] ClusterRoles -- fallback view is enough
- [x] Roles --fallback view is enough
- [x] RoleBindings --fallback view is enough
- [x] CONFIGMAPS
- [x] STATEFULSETS -- fallback view is enough
- [x] DEAMONSET
- [x] PV
- [x] PVC
- [x] SA
- [x] INGRESS -- fallback view is enough
- [x] Fallback view

**Comment by idelice** [comment]
Configmaps is done in PR #42 .

**Comment by Ramilito** [comment]
crds added in #154 
daemonsets added in #153

**Comment by Ramilito** [comment]
pv added in #155 
pvs added in #161 
sa added in #162

**Comment by Ramilito** [comment]
crb added in #173

**Comment by Ramilito** [comment]
With the awesome fallback view by @mosheavni, I think we can close this PR! Really great feature ❤️
