### ISSUE TITLE
feat: apply label filters

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#242]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Sometimes I grab a label from somewhere and want to see pods or ingresses or whatever that relates to that label
Maybe some small float/input box for applying a labelSelector to the current view?
some of the logic is already here:
https://github.com/Ramilito/kubectl.nvim/pull/225/files#diff-8f3fd4a79f3dccfbc4225f7a209dee6abd01efdbb3dcacd6ce66ac372cf5e71bR170

**Describe alternatives you've considered**

**Additional context**

**Comment by Ramilito** [comment]
Should this be only for current view? Would it be an and/or operation together with the other filters/namespace selection?

I don't think it's too hard to implement, the kubernetes api takes a labelselector/fieldselector as a query parameter, it would look like this:
```
  http://localhost:8080/api/v1/namespaces/tools/pods?labelSelector=app%3Dechoserver&pretty=false
```

**Comment by mosheavni** [comment]
> Should this be only for current view? Would it be an and/or operation together with the other filters/namespace selection?
> 
> I don't think it's too hard to implement, the kubernetes api takes a labelselector/fieldselector as a query parameter, it would look like this:
> 
> ```
>   http://localhost:8080/api/v1/namespaces/tools/pods?labelSelector=app%3Dechoserver&pretty=false
> ```

I think I'd like it to be saved into the state, per-view
on ingresses I would see label filter: `-l label1=y`
on deployments `-l label2=z`
so on..
it's also best to save the session on every `:Kubectx`
the filters even save when the view is changed.

**Comment by Ramilito** [comment]
That sounds like a nice feature to have.

About the saving state, I really don't see a need to save it to the config file until we leave neovim. 
How I see it working is that we have state variables that we work with during the neovim lifetime and when we leave neovim we save that down.
That way we don't get weird unexpected behaviours where things are happening throughout the session.

**Comment by mosheavni** [comment]
> That sounds like a nice feature to have.
> 
> About the saving state, I really don't see a need to save it to the config file until we leave neovim. How I see it working is that we have state variables that we work with during the neovim lifetime and when we leave neovim we save that down. That way we don't get weird unexpected behaviours where things are happening throughout the session.

sure, as long as the session remembers that we have a filter, and reapply it when we change contexts or views, that's fine

**Comment by Ramilito** [comment]
yeah exactly, I'm just trying to have an abstraction between them, but it should work as you describe it

**Comment by mosheavni** [comment]
i think i'll start working on this soon. filtering/seeing labels quickly is really useful for me

**Comment by Ramilito** [comment]
Let me know if you need anything!
