### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#247]
The plugin has many changes
many of the gifs are not up-to-date
we can also print better the exported functions: `.open()` `.close()` `.toggle()`

- [x] Add instructions on how to change keymappings
- [x] Add instructions on how to change theme (list our hl groups and an example)
- [ ] Update gifs

**Comment by Ramilito** [comment]
Awesome work with the docs, I added the update gifs task above, anything else we should do?

**Comment by mosheavni** [comment]
Just in general document some more features
