### ISSUE TITLE
feat: marks in views

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#25]
**Describe the solution you'd like**

Mark different pods,services etc. for quick navigations (e.g. set mark "a" on pod "foo-pod" and "b" on "foo-configmap" etc.)

**Additional context**

**Comment by mosheavni** [comment]
is using the vim marks not enough?
`mM` on view 1
`mN` on view 2
`\`M` to go to view 1
`\`N` to go to view 2

**Comment by Ramilito** [comment]
No this can be closed, working as the issue ment it to, at that time it didn't work well!
