### ISSUE TITLE
flickering colors

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#262]
**Describe the bug**
when moving the cursor, it seems that the highlights are getting reset and that looks like flickering

![2024-08-27_00-18-40 (1)](https://github.com/user-attachments/assets/8cebb556-6c25-40e2-bf86-933b71882292)
(the gif kinda slows it down, it's more pronounced in actual usage)

**To Reproduce**

2. Press '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by Ramilito** [comment]
This is fine now right?
