### ISSUE TITLE
chore: option to op-out of informer 

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#274]
The Resourcebuilder:view starts an informer on all curl cmds, that's a problem when getting a resource that doesn't support the watch feature such as metrics.

Add an option such as:
```
      if opts.cmd == "curl" and opts.with_informer then
        informer.start(builder)
      end

```
And clean up the metrics check in informer.lua

**Comment by mosheavni** [comment]
https://github.com/Ramilito/kubectl.nvim/pull/275
