### ISSUE TITLE
completion suggestion remembering last time

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#289]
**Describe the bug**
When I use completion, whether on the filter or namespace menu, I write something, trigger `<Tab>` a couple of times, then I delete everything, write something new and trigger `<Tab>`, the completion remembers my last choice instead of resetting.

I'll try to demonstrate
- completion for `arg` works
- remove it
- completion for `kube` works
- remove it
- completion for `fa` gives me the next result of the previous `kube`
- remove it
- completion for `fal` gives me result for `kube`

![2024-08-29_13-58-52 (1)](https://github.com/user-attachments/assets/0b6689fd-3373-4f2c-a134-c5be8909c7fb)

**To Reproduce**

2. Press '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by Ramilito** [comment]
Interesting 🤔

**Comment by Ramilito** [comment]
the issue made sense when looking into it, it was caused by us not resetting when the user clears the input field and only reacting on the next tab

**Comment by mosheavni** [comment]
thanks!!
