### ISSUE TITLE
logs should just refresh when we toggle prefix or timestamp

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#292]
**Is your feature request related to a problem? Please describe.**
when toggling timestamp and prefix on logs view, the view should not close and reopen:
https://github.com/Ramilito/kubectl.nvim/blob/b65294533ba0e82db637b23e87d20f914dddef3f/ftplugin/k8s_pod_logs.lua#L41-L42

we can just call logs again with `--since=1s` and keep the same buffer, just as we do when we follow.
This will improve times for pods with very high amount of log lines

just like tail, we should 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mosheavni** [comment]
> To do that we need to solve another thing, when running view.Logs(), in the buffer.lua file, we are creating a window each time. So if we don't have the vim.cmd.close(), we will end up with multiple windows on top of each other. You can test it by:
> 
> 1. removing the close
> 2. open logs
> 3. toggling prefix
> 4. then pressing q once, you will see it requires two taps.
> 
> Not saying we should keep the close, just mentioning that we need to not create a new window.

yeah I see. what about just saving the log lines and know how to split the timestamp and prefix so you can easily add them using an in-memory table?
or that could be too heavy

**Comment by Ramilito** [comment]
If we don't solve the window thing then that would definitely be an option! But I feel that we would get a lot of stability if we didn't recreate the window

**Comment by Ramilito** [comment]
Started some work on this in #297

**Comment by Ramilito** [comment]
I split the change up from #297 to #298 to make a smaller PR since the event handler approach might take some more time.

**Comment by mosheavni** [comment]
thanks @Ramilito 
it seems toggling the options still refreshes the entire float buffer. maybe it's the same window but the `logs` command just retriggers, which is a heavy operation if you have many many logs in a container/pod

**Comment by Ramilito** [comment]
Oh now I understand what you meant before...I don't think parsing the logs would be feasible in both directions, removing a timestamp could be fine but adding it back would be quite the effort.

How about this instead, adding a limit with a low default, say 200 rows that we can change?
