### ISSUE TITLE
feat: enhanced kubectl apply

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#303]
We should display more info than filename in the prompt.
For example, current namespace and context.
A diff maybe?

**Comment by Ramilito** [comment]
@mosheavni what do you think? I'm always scared to press apply since I'm not 100% sure what will be the consequences

**Comment by mosheavni** [comment]
maybe implementing a basic diff (not using any external program) of the changes and a confirmation buffer?

**Comment by Ramilito** [comment]
Yeah my thoughts as well

**Comment by Ramilito** [comment]
Fixed by #326
