### ISSUE TITLE
heavy log crashes neovim

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#307]
**Describe the bug**
by default, opening logs doesn't limit the `--since=` flag, and for me, when I try to view logs of a REALLY heavy pod (that has > 100,000 log lines) it crashes neovim after like 10 seconds

we need to set something sane like `--since=1m` by default
or you have other suggestions?

**To Reproduce**

2. Press '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by Ramilito** [comment]
Yeah I think using the since prop sounds like a great idea, but we might need to make it editable, there is also the limit-bytes option if we want to use that?

**Comment by Ramilito** [comment]
I settled for 5m as a default, in the end I think this should be a configuration option but let me know if 5m is too much
