### ISSUE TITLE
header is dancing when on filter

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#313]
not sure if it's only on filter but you can clearly see what I mean by dancing here:
![2024-09-18_13-13-03 (1)](https://github.com/user-attachments/assets/cdb11f0c-ad0c-49cc-8b8b-4bff94c2bedf)

**Comment by Ramilito** [comment]
I've seen that, I think it's caused by the unicode character we use for the dash, I need to test it more but I think it needs to use `*strdisplaywidth` when calculating widths

**Comment by Ramilito** [comment]
hmm, I remember having this issue a while ago but I'm not able to get it again. Do you do anything special or is it always there? What terminal do you use?

**Comment by mosheavni** [comment]
> hmm, I remember having this issue a while ago but I'm not able to get it again. Do you do anything special or is it always there? What terminal do you use?

it's always like that. I'm using iTerm2 nightly (`Build 3.5.3beta1`)
