### ISSUE TITLE
Bug: overview view crashing vim

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#350]
@mosheavni could you add some details?

I'm guessing it's probably too many curl commands at the same time or too many results

**Comment by mosheavni** [comment]
first I'd truncate the nodes column, I have many nodes in my clusters and I'd want to see the top consuming and make all fit into one screen. Scrolling down is not as fun.

after a while, I'm just thrown out of vim, no errors, no nothing. next thing I see is my shell prompt, like this:
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/70dfe932-bf34-4457-ae3d-a38187665d05">

**Comment by Ramilito** [comment]
That's a lot of nodes 😅, displaying only top 10 now, also think I find the memory leak. Would be awesome if you could try it out?

**Comment by mosheavni** [comment]
looks better, I'll see if it's crashing again.
<img width="425" alt="image" src="https://github.com/user-attachments/assets/d92b2d65-192b-4276-a2ce-54e09d936d56">
do you know why the column titles are going over the edge?

**Comment by mosheavni** [comment]
also, just now:
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/187bd5d6-3664-47f7-8550-8a58673498ac">

**Comment by Ramilito** [comment]
Hmm not sure, will look into that.

Fixed the status nil classic error...

**Comment by Ramilito** [comment]
@mosheavni the width should be similar to our normal table now as well.

**Comment by mosheavni** [comment]
nice improvements!
events are overflowing since they are almost always long lines
i think events should be on their own line
<img width="991" alt="image" src="https://github.com/user-attachments/assets/6cbff0d7-ab6d-442f-8fb1-d9ef667f1531">

**Comment by Ramilito** [comment]
Hmm this is a conundrum, the idea is that you are supposed to be able to choose how many columns you want on a row, so I can't guarantee that the events will be on it's own row. Added a config option for this.

How about I remove the object name and add a reasonable limit to the msg and a ... at the end if it exceeds the limit?

**Comment by Ramilito** [comment]
@mosheavni Did a rework on how the grid layout is setup since the initial was to dynamically adjust based on a max_column per row setting, which made it harder to consider very long rows such as the events column.
The new implementation takes a layout instead in the get_headers section where you specify what columns go in what row, looks like this:
![image](https://github.com/user-attachments/assets/217d427d-3054-4cba-bb62-1e0d766b39c8)

**Comment by mosheavni** [comment]
> @mosheavni Did a rework on how the grid layout is setup since the initial was to dynamically adjust based on a max_column per row setting, which made it harder to consider very long rows such as the events column. The new implementation takes a layout instead in the get_headers section where you specify what columns go in what row, looks like this: ![image](https://private-user-images.githubusercontent.com/8473233/371794339-217d427d-3054-4cba-bb62-1e0d766b39c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NTgyMzEsIm5iZiI6MTcyNzU1NzkzMSwicGF0aCI6Ii84NDczMjMzLzM3MTc5NDMzOS0yMTdkNDI3ZC0zMDU0LTRjYmEtYmI2Mi0xZTBkNzY2YjM5YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMjExMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA5YzkxNGZlMjRmMWE0NzQ5ZDI1NDZjMGE5MWJjNGY0MzhkNjdkYzliYzBhNmU3YWY3MGJlNGMyZDAzYzU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JOWoRL5mcQBSqIlTkhwRcPGCC2-H8Px87_l7u39vIac)

looks great also on my side :) love it
