### ISSUE TITLE
Global keymaps available in places it shouldn't

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#353]
### Scenario
You are watching the logs for a pod and accidentally press one of the global keymaps e.g. `1` or `2`, now, your log view is either showing deployments or pods in pods.

### Steps to reproduce
1. show logs for a pod
2. press `1` 

### Expected
pressing `1` (or any other global keymaps for that matter) shouldn't change the view.

**Comment by Ramilito** [comment]
That's fair, I'll see what I can do!

It should have been as easy as checking if window is relative == "" before registering the global mappings but a quick test I made didn't work

**Comment by Ramilito** [comment]
Fixed!
