### ISSUE TITLE
toggle auto-filter

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#366]
filter view previously didn't auto search when you choose from history,
I really liked being able to click `enter` on a filter then add/remove/change it and then apply it
Can we allow the user to choose whether to auto filter when clicking `enter` or just fill the prompt?
Also, when we just fill the prompt, the cursor is at the start of the line (we had this before, remember we had this issue before? @Ramilito)

So when the feature of auto-filter is turned off, I want the cursor to be at the end of the filter term.

Thanks buddy.

**Comment by Ramilito** [comment]
Fixed! the default is enabled though so put this in your config:

```
        filter = {
          apply_on_select_from_history = false,
        },

```

**Comment by Ramilito** [comment]
> Thanks buddy.

Anytime!
