### ISSUE TITLE
feat: helm view

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#373]
view for helm deployments

**Comment by Ramilito** [comment]
What does that mean? I usually don't use helm to deploy stuff (helm template outputs instead), doesn't the fallback view show those? or do we want custom actions on the helm stuff?

**Comment by mosheavni** [comment]
custom actions on helm stuff. just like on k9s
TBH, I don't use helm directly myself as well, I use ArgoCD but I guess some people could benefit from that.
