### ISSUE TITLE
hints on port-forward are duplicated

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#392]
I have a custom mapping for `<Plug>(kubectl.kill)`
for some reason, on the port-forward float (maybe in other places as well) I see both mappings, original, and my override:
<img width="819" alt="image" src="https://github.com/user-attachments/assets/4a2298f0-9b44-4704-933b-7c1c7cc24696">

**Comment by Ramilito** [comment]
Yeah I can see why, the is_plug_mapped function seems to not be working properly

**Comment by Ramilito** [comment]
this is a bit annoying, it's basically a race condition, when we open the plugin the ftplugin will run but the keymaps aren't set until the next ui loop.
If we add a delay it will work but we get a bunch of jumping hints. I really don't want to create a DSL for mapping...do you have any ideas?

**Comment by Ramilito** [comment]
This should work now, I think we have minimal jumping (I can't see any at all but maybe on slow machines).

Keypoints:
- We have to call is_plug_mapped in a vim.schedule AFTER we have registered the plug function.
