### ISSUE TITLE
[Bug] Navigate back from deployments

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#40]
**Steps**
1. Kubectl get deployments 
2. Navigate to the pod

**Expectation**
I should be able to navigate back to the deployment view, but right now, I can't.

**Comment by Ramilito** [comment]
I looked at your fork and it seems to be missing this: https://github.com/Ramilito/kubectl.nvim/blob/4bd00fd6778bdf3fe1664adc800d791acefb0ae5/ftplugin/k8s_pods.lua#L54

**Comment by idelice** [comment]
> Isn't backspace working for that? I just tried it and worked fine, could it be a binding issue?

You're correct. I just didn't know there was a keybinding for that
