### ISSUE TITLE
informer error on sort_events_by_resource_version

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#402]
Again, something I have no clue how to recreate, but it seems like the fix is simple
Also on this time, it crashed nvim

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/2345d7a5-191b-49ed-8c9a-5275c46596b3">

**Comment by Ramilito** [comment]
Would love what the event looks like when this happens but for now I just added a check, the simple fix. Not sure if this will give another issue further down the line though.

**Comment by Ramilito** [comment]
Yeah it's time to take that on
