### ISSUE TITLE
[Feature] Add shortcuts for different views

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#41]
For the sake of simplicity, instead of typing Kubectl commands all the time, I'm proposing a simpler solution.

Add shortcuts for each view e.g.

Pressing "1" would trigger the "pods" view
Pressing "2" would trigger the "deployments" view
Pressing "3" would trigger the "configmaps" view 
.. and so on.

And these shortcuts should be configurable from the user site.

And the shortcuts should be visible in the UI i.e. maybe under "hints"? 

Why? because, if you are working with kubernetes _a lot_, you know the annoyance of navigating back and fort between each view all the time. This would save us that!

**Comment by idelice** [comment]
I'm working on a PR for this.. let's see how ugly my lua code is gonna be :)

**Comment by Ramilito** [comment]
I love it!

How about putting them in the g? help buffer?

**Comment by Ramilito** [comment]
Solved by #47, awesome work @idelice!
