### ISSUE TITLE
Logs - changing prefix/history/timestamp not refreshed on tail

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#421]
**Describe the bug**
When opening a log, then `f` to follow, then `gt` to toggle timestamp, the first output is indeed toggled, but the follow that we started previously doesn't contain the new property

**To Reproduce**
1. Open pod logs
2. start tailing (follow)
3. toggle timestamp
4. now you see the logs are still with timestamp even though we disabled it

**Expected behavior**
tail/follow should have the same flags defined by the options toggled

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. OSX]
 - Neovim version [e.g. 0.10]

**Additional context**

**Comment by Ramilito** [comment]
Good catch, makes sense since it's still using the old variables
