### ISSUE TITLE
feat: Display server last heartbeat and version

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#422]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Sometimes my vpn gets disconnected, sometimes I'm not sure whether I need to reload the view.
If we could see some indication of when was the last successful command to the server, it can be really helpful
Maybe in the context part of the header?
Also if we could print the server and client version we're using, that could provide more info about the cluster.
both options need to be optional

**Describe alternatives you've considered**

**Additional context**

**Comment by Ramilito** [comment]
![image](https://github.com/user-attachments/assets/3b3f8695-ced2-4547-91ce-83e443b7f0fe)

![image](https://github.com/user-attachments/assets/923aaf9d-5806-4979-a39f-63ad97d9c2ba)


How about this?

**Comment by Ramilito** [comment]
fixed heartbeat in #425 and in #424 😅

**Comment by mosheavni** [comment]
fixed versions in #427
