### ISSUE TITLE
How the heck do you use the plugin after you install it?

### ISSUE THREAD

**Issue by icsy7867** [Ramilito/kubectl.nvim#428]
**Describe the bug**
This is 100% user error... the lazy vim documentation is a bit lacking for someone completely unused the nvim...
So I got nvim installed, then got lazyvim setup and installed.  Then following their documentation, I have kubectl.nvim installed...

![image](https://github.com/user-attachments/assets/5f172f62-b805-4fab-b914-fee87ac304dc)

So lazyvim loads... but I cant for the life of me figure out how to use this tool.
![image](https://github.com/user-attachments/assets/ab9e9a78-23de-4436-970a-d0887b02e9ec)

I added the kubectl filder from the git repo untder ~/.config/nvim/lua

and I added a kubectl.lua under ~/.config/nvim/lua/plugins
(per your README)

I also see you have a file under "Configuration" -> "Setup" on the readme... but I can't tell if I am supposed to put that somewhere, or if it is just for reference?  I am sure this is user error... but I can't seem to figure out what I am doing wrong.

**Environment (please complete the following information):**
RHEL9

**Comment by icsy7867** [comment]
From vim.keymap.set("n", "<leader>k", '<cmd>lua require("kubectl").toggle()<cr>', { noremap = true, silent = true })

I would assume I need to just press "n"? But this just opens a new file for editing.

**Comment by Ramilito** [comment]
Hi! I'm glad you want to try out the plugin! we have worked hard on it and hope you enjoy it!

You should be able to ignore the setup for now until you want to customize the plugin.

> From vim.keymap.set("n", "k", 'lua require("kubectl").toggle()', { noremap = true, silent = true })
> I would assume I need to just press "n"? But this just opens a new file for editing.

That is incorrect! The "n" is to say what vim mode this binding should be applied to, "n" in this case is for normal mode.
In the binding you pasted, "k" would be the correct key to press to toggle this plugin, but you are missing the leader for that binding, in the readme this is the binding:

`vim.keymap.set("n", "<leader>k", '<cmd>lua require("kubectl").toggle()<cr>', { noremap = true, silent = true })`

Do you see the '<leader>k' part, that's the keys you are supposed to press to run the command. normally, leader is <space>

**Comment by icsy7867** [comment]
Thanks for the reply! I think I understand that the leader key is a special key.  So that is actually saying "<leader> + k".

When I hit space, I get a list of shortcuts.  But when I hit "k" my cursor just moves up the list.
![image](https://github.com/user-attachments/assets/3a2a6233-b98e-4726-8cc3-0d1e8fdf700b)

**Comment by Ramilito** [comment]
Could you paste the code that you create the mapping with? Just want to make sure it's the correct one!

**Comment by Ramilito** [comment]
Maybe you could make your nvim config into public repo? I'd surely be able to find the error then

**Comment by icsy7867** [comment]
Ohhh no I think I got it!

I thought the keymap was already loaded by default. I didnt realize I needed to actually add it to config/keymaps.lua !

```
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
vim.keymap.set("n", "<leader>k", '<cmd>lua require("kubectl").toggle()<cr>', { noremap = true, silent = true })
```

Definitely user error as I try to figure out nvim/lazyvim! Thanks!

**Comment by Ramilito** [comment]
Glad it worked!!
