### ISSUE TITLE
bug: Unable to connect to the server: getting credentials

### ISSUE THREAD

**Issue by Keyruu** [Ramilito/kubectl.nvim#432]
**Describe the bug**
When I start kubectl.nvim it throws this error:
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 255 
Error: The config profile (eks-cluster) could not be found
My guess is that my PATH isn't being respected or something.

**To Reproduce**

1. Use kubectl.nvim with an EKS cluster

**Expected behavior**
It should not throw the error

**Environment (please complete the following information):**
 - OS: OSX
 - Neovim version 0.10.1

**Additional context**
I am using the fish shell for shell usage, if that matters. I don't have anything special provided to the plugin just: `require("kubectl").setup()`.

**Comment by Ramilito** [comment]
Your guess is correct!
We use session instances without any environment variables set except KUBECONFIG and PATH, mostly so we don't get any conflicts but also for safety/privacy.
You can set the aws profile env like this:

```lua
require('kubectl').setup {
  kubectl_cmd = {
    env = {
      KUBECONFIG = "$XDG_CONFIG_HOME/kube/config",
      KUBECACHEDIR = "$XDG_CACHE_HOME/kube",
    }
  }
}
```

**Comment by Keyruu** [comment]
I actually had some issue with my auth to AWS. But thank you for the help!

**Comment by dc-jbw** [comment]
I have a similar issue, albeit only on macOS, but it doesn't go away even if I explicitly configure the plugin environment to point to my proper K8s config and cache. The error I get is: 
```
Unable to locate credentials. You can configure credentials by running "aws configure".  
```
That's more than a bit surprising because I can run any `kubectl` command from either that same directory or even inside a terminal in the same Neovim session. But then my AWS creds are basically defined via `direnv` setting environment variables found in a `.envrc` file because I work with multiple AWS accounts from multiple folders. Is there any way to tell the plugin to respect those environment variables? Thanks in advance.

**Comment by dc-jbw** [comment]
For others who may suffer from a similar problem, I'll describe and provide my solution. I'm essentially counting on the `direnv` utility to configure my AWS CLI via environment variables stored in `.envrc` files. Those variables are part of the environment when I launch Neovim, and they're part of any terminal shell I open in Neovim, but the K8s plugin basically discards all that information when it's running commands. So my solution, shown below in a couple code snippets from my K8s file spec, relies on a function to pull those four specific environment variables and put them into a table that can subsequently be passed to the plugin's environment options at initialization. 

```language-lua
local function get_aws_env_vars()
    local result = {}
    local varNames = { "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_DEFAULT_REGION", "AWS_DEFAULT_OUTPUT" }
    for _, var in ipairs(varNames) do
        result[var] = os.getenv(var)
    end
    return result
end

return {
    {
        "ramilito/kubectl.nvim",
        keys = {
            { "<C-k>", function () require("kubectl").toggle() end, desc = "Toggle K8s", mode = "n" },
        },
        opts = {
            kubectl_cmd = {
                cmd = "kubectl",
                env = get_aws_env_vars(),
            }
        },
    },
}


```

I hope that helps somebody else. Cheers!

**Comment by Ramilito** [comment]
Awesomely solved 👏
I will write this to the wiki as well.

On another note, the choice to not start sub processes with inherited envs is out of respect for the user and a trust thing, we could offer an opt out of it through configuration if there is interest .

Maybe it's just me but I would feel safer if my programs didn't look or used my env secrets without explicitly being allowed to.
