### ISSUE TITLE
feat: ability to see previous pod logs

### ISSUE THREAD

**Issue by jemag** [Ramilito/kubectl.nvim#454]
**Is your feature request related to a problem? Please describe.**
Currently it doesn't seem (unless I missed it), that we can see the logs of the pod prior to a restart.

**Describe the solution you'd like**
Be able to consult the logs prior to a restart, aka `kubectl logs XXXX -p`

**Describe alternatives you've considered**
Use normal kubectl

**Additional context**
In the log window, perhaps add a keybind to see the previous logs, e.g.:
![image](https://github.com/user-attachments/assets/eb285cad-4569-4771-b6da-003a99c298ea)

**Comment by mosheavni** [comment]
I agree this is a must-have!

**Comment by Ramilito** [comment]
Added!
