### ISSUE TITLE
Close command doesn't clean up properly

### ISSUE THREAD

**Issue by eslamallamAdri** [Ramilito/kubectl.nvim#474]
**Describe the bug**
After closing kubectl with require('kubectl').close() I keep getting a message saying "curl: (7) Failed to connect to 127.0.0.1 port 46559 after 0 ms: Couldn't connect to server" every 1 second. This started happening recently.

**To Reproduce**
1. Open kubectl with `require('kubectl').open()`
2. Close it with `require('kubectl').close()`

**Expected behavior**
the plugin should stop trying to reach that url after closing it

**Screenshots**
![image](https://github.com/user-attachments/assets/1010abd5-1f1f-4cc4-b5aa-005f2c45a9e5)

**Environment (please complete the following information):**
 - OS: Fedora 40
 - NVIM v0.11.0-dev+1003-ged794c9a1
   Build type: RelWithDebInfo
   LuaJIT 2.1.1720049189

**Additional context**
in my .kube/config, I'm connecting through a socks5 proxy with cloudflare argo.

**Comment by Ramilito** [comment]
Hmm that's interesting, my bet would be that the informer isn't shutting down, will look into it, thank you for reporting this!

**Comment by Ramilito** [comment]
We apparently didn't dispose of the heartbeat timer properly, this should be fixed now!
