### ISSUE TITLE
init containers not showing on containers view

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#477]
this issue is persistent, not a glitch :)
I don't see init containers on the containers view.
one example:

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/27022e03-54c4-4f98-aeda-a9ab9eac8d68">

**Comment by Ramilito** [comment]
Fixed in #471

**Comment by Ramilito** [comment]
<img width="979" alt="image" src="https://github.com/user-attachments/assets/6482ad81-51cf-4208-a729-d846ab770ec1">
