### ISSUE TITLE
"Completed" pods should be colored green

### ISSUE THREAD

**Issue by mosheavni** [Ramilito/kubectl.nvim#489]
<img width="266" alt="image" src="https://github.com/user-attachments/assets/0102e5d7-e6bb-42fc-9872-a2fca4e64620">

I know we mark completed jobs with green color but there are also random pods that are not part of a job and their task is to run and finish and they should be green as well.

I think we can depend on the status being "Completed" and based on that mark the pod `READY` column as green

**Comment by Ramilito** [comment]
That's a great idea!
