### ISSUE TITLE
feat: port-forward pop-up window

### ISSUE THREAD

**Issue by assafdori** [Ramilito/kubectl.nvim#496]
**Is your feature request related to a problem? Please describe.**

When running for example ```kubectl run nginx --image nginx``` and trying to use ```gp``` to port-forward, you're faced with an error message that the pod has no ports mapped to it.

**Describe the solution you'd like**
Some sort of pop-up such as the one k9s provides.

**Describe alternatives you've considered**
I think a simple pop-up such as the one showed below should be sufficient.

**Additional context**

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/fdc9a80b-dc5e-4e04-a665-ea91334ef536">

**Comment by Ramilito** [comment]
Did a hotfix to allow this, it's missing the help text that k9s has but should work!
