### ISSUE TITLE
bug: using the global mapping for closing plugin causing mappings to be destroyed when opening the plugin again

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#50]
Steps
1. open plugin
2. press "1" or "3" (or any other navigation)
3. do `<leader>k` to close the plugin
4. open plugin
5. do step *2* again

Expectation
Everything should work fine as before but it doesn't. shortcuts not working

**Comment by Ramilito** [comment]
Nice catch!
