### ISSUE TITLE
feat: make skew version warning optional

### ISSUE THREAD

**Issue by roman-kiselenko** [Ramilito/kubectl.nvim#506]
**Is your feature request related to a problem? Please describe.**

If the client version is different from the server. A warning popup as message:

```
WARNING: version difference between client (1.31) and server (1.28) exceeds the supported minor version skew of +/-1
```

**Describe the solution you'd like**

Make this warning optional, so that when it opens it does not interrupt the display.

**Describe alternatives you've considered**

none

**Additional context**

I would like to try adding this myself.

https://github.com/user-attachments/assets/fb543302-7d91-454b-accd-42c4f2de9209

**Comment by Ramilito** [comment]
Hi! Awesome suggestion! 
You are more than welcome to try adding this yourself, let me know if you need anything!
