### ISSUE TITLE
Do not rely on auto_refresh to act on a command

### ISSUE THREAD

**Issue by jemag** [Ramilito/kubectl.nvim#524]
**Is your feature request related to a problem? Please describe.**
Invoking  actions such as `<Plug>(kubectl.view_overview)` or `<Plug>(kubectl.toggle_headers)` should not depend on the refresh interval or manual refresh.

**Describe the solution you'd like**
Currently using actions with a significant `auto_refresh.interval` specified results in a poor experience with delays. For example, here I have a `5000` interval configured and you can see there is a significant delay between invoking the keys to toggle the headers and it happening:
![wezterm-gui_CLUAJ1fvvv](https://github.com/user-attachments/assets/7ba43a26-0cc3-47a1-a26c-48b8a2abb920)

**Describe alternatives you've considered**
An alternative would be to add the refresh mapping on top of every action mapping, although this would become quickly tedious for the end-user and it would also not be as convenient since the `refresh` action  generates a notification.

**Comment by Ramilito** [comment]
Just tried it and yeah...that's not a great experience.
Although, the `auto_refresh` should probably be named `auto_redraw` since the `gr` refresh is not the same, the current `auto_refresh` does not produce a notification and does not do any fetch via the kubernetes api. With that known, would you find any reason to have a high auto_refresh? I use a refresh rate of 200ms, and it gives me a rather snappy UI.

One way to solve this is to introduce a new `redraw_rate` option that is very low and redesign `auto_fresh` to actually do a refresh with a supressed refresh message.

**Comment by jemag** [comment]
Thank you for the clarification. 

At work I have to use a slower PC and a high `auto_refresh.interval` does increase my CPU usage (from `5000` interval using about 2-5% CPU, and with `300` interval using 10-15%)

I think it would be useful to split the `redraw_rate` and the `auto_refresh` option either way since some individuals with fast connections could perhaps want fast redraw, slow refresh.

Regarding my issue, would it not be possible to simply trigger a redraw when invoking such actions?
 I assume that someone hitting the mapping to `toggle_headers` or `view_overview` would like those to happen right away in any case. Having the redraw being part of these actions would make it instant, and users could still experiment with `redraw_rate` and `auto_refresh` values matching their specific needs.

**Comment by Ramilito** [comment]
> I think it would be useful to split the `redraw_rate` and the `auto_refresh` option either way since some individuals with fast connections could perhaps want fast redraw, slow refresh.

Created a new issue here: #527 

> Regarding my issue, would it not be possible to simply trigger a redraw when invoking such actions? I assume that someone hitting the mapping to `toggle_headers` or `view_overview` would like those to happen right away in any case. Having the redraw being part of these actions would make it instant, and users could still experiment with `redraw_rate` and `auto_refresh` values matching their specific needs.

I agree, have implemented those two to do a redraw here: #526
