### ISSUE TITLE
[Feature] Don't override default navigational keys

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubectl.nvim#56]
**Is your feature request related to a problem? Please describe.**

We use the keys to navigate around so it's counterproductive to use the same keys for commands

**Describe the solution you'd like**

A float that shows available actions, the con is that it would add another keypress for every action which isn't great.

**Describe alternatives you've considered**

Offer configuration for all keys so that users can adjust them instead.

**Comment by idelice** [comment]
Hmm.. maybe instead of using the numbers 1,2,3 etc.. to navigate to each view, we could instead do `<C-1`, `<C-2` and so on for default keybinding.

I'm also for to let the consumer chose their own keybinding.

**Comment by Ramilito** [comment]
I went with the prefix route, specifically the g prefix, this should feel similar to lsp bindings and not interfere with other navigational or other plugins
