### ISSUE TITLE
question about "pending" and "running" state 

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#73]
They have the same color.

Is that on purpose? If so, can i suggest a different color based on the state? Or is it out of this plugins' scope?

<img width="140" alt="Screenshot 2024-07-02 at 19 05 26" src="https://github.com/Ramilito/kubectl.nvim/assets/59118341/db1042f5-13c4-4ef5-bc6d-0dedf23c459c">

**Comment by Ramilito** [comment]
That's a bug, must have happened when I switched how we highlight stuff, #65. It should be a straightforward fix, brb

**Comment by Ramilito** [comment]
hmmm...this is how it's looking for me: 
<img width="590" alt="image" src="https://github.com/Ramilito/kubectl.nvim/assets/8473233/d246e0cc-3f01-4035-8d27-2eefca68ec72">
Are you on latest? could you run this command: ```new | pu=execute('highlight')``` and locate the ones that are prefixed with "Kubectl", I'm mostly interested in KubectlWarning

**Comment by Ramilito** [comment]
nvm I can recreate now, seems to happen whin filtering

**Comment by Ramilito** [comment]
The issue was related to the extmark issue in that we need to filter before setting extmarks, I think it should be fixed now!
