### ISSUE TITLE
feature request: Auto-update container logs every n seconds

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#75]
Right now, if I were to look at new container logs, I have to close the log window, and open it again.

Instead, I suggest some kind of auto-fetching logs every n seconds (could be 2 seconds).

**Comment by Ramilito** [comment]
Have you tried the follow (tail) feature by pressing f?
<img width="996" alt="image" src="https://github.com/Ramilito/kubectl.nvim/assets/8473233/55c63186-acb8-4de2-b28b-7f8ac4785891">

**Comment by idelice** [comment]
It doesn't work. I tested it twice today and nothing really happens.

I'm still interested in auto-fetching every 2 seconds regardless if you "follow" or not

**Comment by Ramilito** [comment]
It should work now with latest, I seem to have missed to convert the output into a table.

> I'm still interested in auto-fetching every 2 seconds regardless if you "follow" or not

I really don't see the reasons to add that since we basically have live tailing (that should work now).
