### ISSUE TITLE
feat: toggling without losing the state

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#77]
**Current behavior**

1. toggle plugin on
2. go to deployment (or any other)
3. toggle plugin off
4. toggle plugin on
5. the initial pod window shows

**Better behavior**

1. toggle plugin on
2. go to deployment (or any other)
3. toggle plugin off
4. toggle plugin on
5. the view from step 2 should show up

**Bonus**
Partial render the plugin e.g. load the UI first and _then_ start fetching resources. This will boost the start-up and navigation time.

**Comment by Ramilito** [comment]
I do like the idea of saving state, not sure how I would fit that in with multiple sessions but I'll give it a shot.

The bonus one is nice as well, I noticed that k9s does it like that and it does feel faster.

**Comment by idelice** [comment]
Maybe we could save it to local file on the users side and pull from that? Gitpad.nvim is doing something like that

**Comment by Ramilito** [comment]
I'll take a look and see what we can do!

**Comment by Ramilito** [comment]
Solved by #164
