### ISSUE TITLE
feat: history on filtering

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#78]
I suggest adding history to the filtering part.

**Scenario**
You are changing some logic in your code base and open the plugin -> filter -> do your thing -> close the plugin -> change some logic -> toggle plugin on -> filter the same value again and repeat.

We can save a lot of time if we had history on the filtering where we could just "enter" on one of the history entries to filter. We should probably add a limit of 5-10 entries so it doesn't get too verbose and destroy the UI

**Comment by Ramilito** [comment]
Awesome suggestion!

Implemented it, please tell me if it works properly for you!

**Comment by idelice** [comment]
Thank you!

If i had one feedback item, it would be that, instead of pressing "enter" twice (one time to select the history item to paste it in the input field and one more time to search by value) - it would be better UX if you only had to press 'enter' once.

**Comment by Ramilito** [comment]
It was intentional actually :D, I believe that offering a chance to modify it to the cost of one enter is worth it. We can evaluate it and see if it's not the case!
