### ISSUE TITLE
bug: you can edit yaml everywhere

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#80]
**Steps to produce**

1. go to deployments
2. set cursor on namespace
3. press "e"

**Actual**

```
error: arguments in resource/name form may not have more than one slash

[Process exited 1]
```

**Expected**

Should only be possible to go inside edit move when cursor is at the resource

**Comment by Ramilito** [comment]
Good catch, it's a bit of a design flaw, we shouldn't be having a cursor above the headers tbh, might refactor that into its own bufffer
